#! /bin/bash
## compress-img: compress jpegs; probably don't use on other image types
## dependencies: imagemagick

## main
convert "$1" -strip -quality 85 -interlace Plane -gaussian-blur 0.05 "compressed-$1"
