#! /bin/bash
## stream to twitch.tv
## issues:
## - add options to specify streamkey, server, inres, outres, etc.

INRES="2560x1440" # input resolution
OUTRES="1920x1080" # output resolution
FPS="30" # target FPS
GOP="60" # i-frame interval, should be double of FPS, 
GOPMIN="30" # min i-frame interval, should be equal to fps, 
THREADS="2" # max 6
CBR="1000k" # constant bitrate (should be between 1000k - 3000k)
QUALITY="ultrafast"  # one of the many FFMPEG preset
STREAM_KEY="$1" # use the terminal command Streaming streamkeyhere to stream your video to twitch or justin
SERVER="$2" # see https://stream.twitch.tv/ingests/ for list

if [[ "$#" -ne 2 ]]; then # incorrect args
	>&2 echo 'stream-twitch: incorrect arguments'
else
	ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0+900,0 -f flv \
		-vcodec libx264 -g $GOP -keyint_min $GOPMIN -b:v $CBR -minrate $CBR -maxrate $CBR -pix_fmt yuv420p\
		-s $OUTRES -preset $QUALITY -tune film -threads $THREADS -strict normal \
		-bufsize $CBR "rtmp://$SERVER.twitch.tv/app/$STREAM_KEY"
fi
